# Generated by Django 5.0.1 on 2024-01-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Ndonga_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Ndonga_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Ndonga_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_Phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.door')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.gate')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.window')),
            ],
        ),
    ]
