# Generated by Django 5.0.1 on 2024-01-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='window',
        ),
        migrations.CreateModel(
            name='Quotation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_Phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.window')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_Phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.gate')),
            ],
        ),
    ]
